nombre = "Diego"
# print(len(nombre))
# print(nombre.find('i'))
# print(nombre.capitalize())
# print(nombre.upper())
# print(nombre.lower())
# print(nombre.isdigit())
# print(nombre.isalpha())
# print(nombre.count('i'))
# print(nombre.replace("g", "8"))
# print(nombre * 3)